services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: latest
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: example
      MYSQL_ROOT_HOST: "%" 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-u", "admin", "-pexample", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s

volumes:
  db_data: {}